FROM mcr.microsoft.com/dotnet/sdk:8.0 as build
WORKDIR /app/build
COPY ./Catalog.Api.csproj ./
RUN dotnet restore 
COPY ./ ./
RUN dotnet build -c Release -o /app/release

FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine as host
WORKDIR /etc/api/catalog
EXPOSE 8080
COPY --from=build /app/release ./
ENTRYPOINT ["dotnet", "/etc/api/catalog/Catalog.Api.dll"]