POST http://localhost:5157/products HTTP/1.1
Content-Type: application/json

{
    "name": "test_product",
    "categories":["test"],
    "description" : "desc",
    "imageFile" : "image",
    "price" : 900
}


GET http://localhost:5157/products 