services:
  catalogdb:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catalogdb
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - postgres-catalog:/var/lib/postgressql/data/
